---
title: "abiotiek waterlopen TVG"
author: "An Leyssen"
date: "`r Sys.Date()`"
output: 
  html_document:
    number_sections: no
    toc: TRUE
    toc_float:
      collapsed: FALSE
      smooth_scroll: FALSE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE, 
  eval = TRUE,  
  cache = FALSE, 
  autodep = TRUE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 150 / 25.4,
  warning = FALSE,
  error = TRUE,
  message = FALSE)
# library(DBI) 
library(kableExtra)
# library(patchwork)
library(tidyverse)
library(readxl)
# library(googlesheets4)
# library(janitor)
library(lubridate)

# to do: schrap overbodige packages
```

# doel

export/selectie data waterlopen uit AquaChem.

# import data

- abiotische data uit AquaChem   
- bewerkte data (omrekening mg N en mg P)  

```{r}
# lijst relevante staalcodes uit Watina
lijst_waterlopen_watina <- read_xlsx("./data/Watinacodes_meetpunten_waterlopen.xlsx") %>% 
  pull(WATINA_Code) 

# abiotische data van aquachem (to do vernieuwen)
abiotiek <- read.csv2("./data/FactResultAqua_bewerkt_2025-02-19.csv")
abiotiek_ruw <- read.csv2("./data/FactResultAqua_2025-02-19.csv")
```

#  filter relevante data
```{r}
# bewerkte data
abiotiek_bewerkt_WL <- abiotiek %>% 
  filter(FieldSampleID %in% lijst_waterlopen_watina) 
# %>% 
#   mutate(FieldSamplingDate = as_date(FieldSamplingDate))
# indien datums op tijdsschaal

# ruwe data
abiotiek_ruw_WL <- abiotiek_ruw %>% 
  filter(FieldSampleID %in% lijst_waterlopen_watina) 

# hoeveel verschillende FieldSampleID's?
abiotiek_bewerkt_WL %>% 
  select(FieldSampleID) %>% 
  distinct() %>% 
  count()
# 2025-02-12 namiddag: 47 itt 49 in lijst van Jo
# 2025-02-14 ev 48 ok
# TVGR219X is effectief niet gemeten --> moeten er 48 zijn
```

#  figuur meetreeks
```{r}
fig_meetreeks <- abiotiek_bewerkt_WL %>% 
  select(FieldSamplingDate, FieldSampleID) %>% 
  distinct() %>% 
  ggplot(aes(x = FieldSamplingDate, y = FieldSampleID)) +
  geom_point() +
  theme(axis.text.x = element_text(angle=90))
fig_meetreeks

ggsave(plot = fig_meetreeks, 
       filename = "./output/meetreeks_beken.jpg", width = 7, height = 10) 
```

```{r}
abiotiek_bewerkt_WL %>% 
  select(FieldSampleID, FieldSamplingDate, FieldObserver) %>% 
  distinct() %>% 
  arrange(FieldSampleID, FieldSamplingDate) %>% 
  kable() %>% 
  kable_styling() %>% 
  scroll_box(height = "500px")
```

to do opvolgen: datums 2023 lijken niet te kloppen volgens Jo; te checken

#  export data
```{r}
write.csv2(abiotiek_bewerkt_WL, "./output/FactResultAqua_bewerkt_TVG_beken_2025-02-19.csv")
write.csv2(abiotiek_ruw_WL, "./output/FactResultAqua_TVG_beken_2025-02-19.csv")
```
